import Foundation
import CoreData

// MARK: - TrainingProgram

/// A 12-week periodized training program generated by the Pareto engine.
@objc(TrainingProgram)
public class TrainingProgram: NSManagedObject {

    // MARK: - Attributes

    @NSManaged public var id: UUID
    @NSManaged public var name: String
    @NSManaged public var startDate: Date
    @NSManaged public var endDate: Date?
    @NSManaged public var weekCount: Int16
    @NSManaged public var frequency: String
    @NSManaged public var aestheticGoal: String
    @NSManaged public var gymProfileId: UUID?
    @NSManaged public var morphotypeAtCreation: String?
    @NSManaged public var isActive: Bool

    // MARK: - Relationships

    @NSManaged public var userProfile: UserProfile?
    @NSManaged public var weeks: NSOrderedSet?

    // MARK: - Convenience Init

    convenience init(context: NSManagedObjectContext) {
        let entity = NSEntityDescription.entity(forEntityName: "TrainingProgram", in: context)!
        self.init(entity: entity, insertInto: context)
        self.id = UUID()
        self.name = ""
        self.startDate = Date()
        self.weekCount = 12
        self.frequency = ProgramFrequency.fullBody3.rawValue
        self.aestheticGoal = AestheticGoal.greekMale.rawValue
        self.isActive = true
    }

    // MARK: - Computed Helpers

    var parsedFrequency: ProgramFrequency {
        ProgramFrequency(rawValue: frequency) ?? .fullBody3
    }

    var parsedGoal: AestheticGoal {
        AestheticGoal(rawValue: aestheticGoal) ?? .greekMale
    }

    var sortedWeeks: [ProgramWeek] {
        guard let ordered = weeks else { return [] }
        return ordered.array.compactMap { $0 as? ProgramWeek }
            .sorted { $0.weekNumber < $1.weekNumber }
    }

    var currentWeekNumber: Int {
        let daysSinceStart = Calendar.current.dateComponents([.day], from: startDate, to: Date()).day ?? 0
        return min(max(daysSinceStart / 7 + 1, 1), Int(weekCount))
    }
}
